"""Yosys synthesis: RTL -> mapped gate-level netlist + source-annotation JSON."""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

from .config import FlowConfig
from .tools import ToolResult, yosys


@dataclass
class SynthResult:
    ok: bool
    workdir: Path
    netlist: Optional[Path]
    mapped_json: Optional[Path]
    elab_json: Optional[Path]
    cells: int = 0
    area: float = 0.0
    per_module_cells: Dict[str, int] = field(default_factory=dict)
    seconds: float = 0.0
    log: str = ""
    error: str = ""


_STAT_MODULE = re.compile(r"^=== (\S+) ===")
_STAT_CELLS = re.compile(r"^\s+Number of cells:\s+(\d+)")
_STAT_AREA = re.compile(r"Chip area for (?:top )?module '\\?(\S+?)':\s+([0-9.]+)")


def _parse_stat(text: str) -> tuple[int, float, Dict[str, int]]:
    """Parse ``stat -liberty`` output into (total cells, area, per-module cells)."""
    per_module: Dict[str, int] = {}
    total_cells = 0
    area = 0.0
    current: Optional[str] = None
    for line in text.splitlines():
        m = _STAT_MODULE.match(line)
        if m:
            current = m.group(1)
            continue
        m = _STAT_CELLS.match(line)
        if m and current:
            n = int(m.group(1))
            if current == "design hierarchy":
                total_cells = n
            else:
                per_module[current] = n
            continue
        m = _STAT_AREA.search(line)
        if m:
            area = float(m.group(2))
    if total_cells == 0 and per_module:
        total_cells = max(per_module.values())
    return total_cells, area, per_module


def build_script(cfg: FlowConfig, rtl_files: List[Path], rtl_root: Path,
                 workdir: Path) -> str:
    """Return the Yosys script text for one synthesis run.

    Two JSON dumps are produced:

    ``elab.json``   right after elaboration, while every cell still carries the
                    ``src`` attribute Yosys derives from the RTL. This is the
                    file the localiser uses to map netlist objects back to
                    file:line.
    ``mapped.json`` after technology mapping, used for netlist-level queries
                    such as resolving generated-clock divider pins.
    """
    defines = " ".join(f"-D{d}" for d in cfg.bench.defines)
    files = " ".join(f'"{p}"' for p in rtl_files)
    lib = cfg.platform.lib_map
    return f"""# auto-generated by genrtl.synth -- do not edit
read_verilog -sv {defines} -I "{rtl_root}" {files}
hierarchy -check -top {cfg.top}
proc
opt_clean
write_json "{workdir / 'elab.json'}"

synth -nofsm -top {cfg.top}
dfflibmap -liberty "{lib}"
abc -liberty "{lib}" -D {cfg.platform.abc_delay_ps}
setundef -zero
opt_clean -purge

write_json "{workdir / 'mapped.json'}"
write_verilog -noattr "{workdir / 'netlist.v'}"
tee -o stat.txt stat -liberty "{lib}" -top {cfg.top}
"""


def synthesize(cfg: FlowConfig, rtl_files: List[Path], rtl_root: Path,
               workdir: Path, *, name: str = "synth") -> SynthResult:
    workdir.mkdir(parents=True, exist_ok=True)
    script = build_script(cfg, rtl_files, rtl_root, workdir)
    res: ToolResult = yosys(script, workdir=workdir, name=name,
                            binary=cfg.tools.yosys)

    netlist = workdir / "netlist.v"
    mapped = workdir / "mapped.json"
    elab = workdir / "elab.json"
    stat_txt = workdir / "stat.txt"

    if not res.ok or not netlist.is_file():
        return SynthResult(
            ok=False, workdir=workdir, netlist=None, mapped_json=None,
            elab_json=elab if elab.is_file() else None,
            seconds=res.seconds, log=res.tail(40),
            error="yosys synthesis failed",
        )

    cells, area, per_module = _parse_stat(
        stat_txt.read_text() if stat_txt.is_file() else res.stdout)

    return SynthResult(
        ok=True, workdir=workdir, netlist=netlist, mapped_json=mapped,
        elab_json=elab, cells=cells, area=area, per_module_cells=per_module,
        seconds=res.seconds, log=res.tail(10),
    )


def lint(cfg: FlowConfig, rtl_files: List[Path], rtl_root: Path,
         workdir: Path, *, name: str = "lint") -> ToolResult:
    """Cheap syntax/elaboration gate: read + hierarchy check only."""
    defines = " ".join(f"-D{d}" for d in cfg.bench.defines)
    files = " ".join(f'"{p}"' for p in rtl_files)
    script = f"""read_verilog -sv {defines} -I "{rtl_root}" {files}
hierarchy -check -top {cfg.top}
proc
check -assert
"""
    return yosys(script, workdir=workdir, name=name, binary=cfg.tools.yosys,
                 timeout=600)


def load_json_netlist(path: Path) -> dict:
    with path.open() as fh:
        return json.load(fh)
